name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.10.0'
    
    - name: Install dependencies
      run: |
        cd bdd-vite-react
        npm install
    
    - name: Run lint
      run: |
        cd bdd-vite-react
        npm run lint
    
    - name: Build application
      run: |
        cd bdd-vite-react
        npm run build

    - name: Start server
      run: |
        cd bdd-vite-react
        npm run dev &
    
    - name: Wait for server to be ready
      run: |
        cd bdd-vite-react
        npx wait-on http://localhost:5173

    - name: Run unit tests
      run: |
        cd bdd-vite-react
        npm test

    - name: Run BDD tests
      run: |
        cd bdd-vite-react
        npm run bdd:headless